Repository transcom/mymove-docs, pull requests merged in 2022-07, with the labels that each got.

#137 MB-12451 Update Service Object Docs to Include Orchestrator Info and Restructure Service Object Docs
  docs/backend/guides/golang-guide.md
  docs/backend/guides/service-objects.md
  docs/backend/guides/service-objects/_category_.json
  docs/backend/guides/service-objects/getting-started.md
  docs/backend/guides/service-objects/implementation.md
  docs/backend/guides/service-objects/overview.md
  docs/backend/guides/service-objects/set-up-service-subpackage-and-interface.md
  docs/backend/guides/service-objects/structure.md
  docs/backend/guides/service-objects/usage.md
  docs/backend/guides/service-objects/validation.md
  docs/backend/guides/service-validation.md
  docs/backend/guides/use-stateless-services-with-app-context.md
  docs/backend/setup/database-migrations.md
  docs/tools/mockery/generate-mocks-with-mockery.md
  utils/redirect-backend.js
Labels: A-Team

#181 MB-13121 Remove unnecessary direct dependencies
  package.json
  yarn.lock
Labels: dependencies, A-Team

#186 [ MB-13238 ] Link to ECS docs in Confluence
  docs/backend/guides/ghc/ghc-import-pricing-production.md
Labels: documentation, Pamplemoose, ready-to-merge, infra, bug
