Repository transcom/mymove-docs, pull requests merged in 2022-01, with the labels that each got.

#57 [MB-10562] Update dependabot links to reflect annexation into GitHub
  docs/tools/dependabot/dependency-update-process-with-dependabot.md
  docs/tools/dependabot/manage-dependabot.md
Labels: A-Team

#106 Update the homepage
  LICENSE
  docs/tutorial/intro.md
  docusaurus.config.js
  src/components/HomepageFeatures.js
  src/components/HomepageFeatures.module.css
  src/css/custom.css
  src/pages/index.js
Labels: enhancement

#107 Fix the build
  .github/workflows/test-builds.yml
  docusaurus.config.js
  src/components/HomepageFeatures.js
Labels: bug

#108 MB-10593 Move locust docs from load testing repo to here
  .gitignore
  docs/tools/locust/adding-or-editing-load-tests.md
  docs/tools/locust/api-parsers.md
  docs/tools/locust/fake-data-generation.md
  docs/tools/locust/local-load-test-setup.md
  docs/tools/locust/locust.md
  docs/tools/locust/locustfile.md
  docs/tools/locust/running-load-tests.md
  docs/tools/locust/running-locust-from-aws.md
  docs/tools/locust/running-locust-locally.md
  docs/tools/locust/taskset.md
  docs/tools/locust/working-with-load-tests.md
  sidebars.js
  vale/Vocab/OSS-Docs/accept.txt
Labels: A-Team

#110 Update nix setup
  .envrc
  nix/default.nix
  nix/update.sh
Labels: A-Team
