Repository transcom/mymove-docs, pull requests merged in 2022-11, with the labels that each got.

#227 [MB-11988] Create a History & Audit Logging Guide
  docs/backend/guides/guide-to-history-and-audit-logging.md
Labels: ready-to-merge

#224 Migrated manage dependabot to Confluence
  docs/tools/dependabot/dependency-update-process-with-dependabot.md
  docs/tools/dependabot/manage-dependabot.md
  sidebars.js
  utils/redirect-tools.js
Labels: documentation

#239 [ c-documentation ] Deleting the User Manangement page from public docs
  docs/about/security/user-management.md
Labels: documentation, security, help wanted
