Repository transcom/mymove-docs, pull requests merged in 2022-06, with the labels that each got.

#139 Add a dependabot.yml to keep node and gh action deps up to date
  .github/dependabot.yml
Labels: A-Team

#155 Update dependencies
  .node-version
  docusaurus.config.js
  nix/default.nix
  package.json
  utils/redirect-tools.js
  yarn.lock
Labels: Pamplemoose, ready-to-merge, dependencies, enhancement

#158 Upgrade node for the deployment
  .github/workflows/deploy.yml
Labels: Pamplemoose, ready-to-merge

#157 [ MB-9033 ] Using React-App-Rewired
  docs/adrs/0072-using-react-app-rewired.md
  vale/Vocab/OSS-Docs/accept.txt
Labels: Pamplemoose, ready-to-merge

#162 Make light theme oceanicNext
  docusaurus.config.js
Labels: Pamplemoose, ready-to-merge, bug

#163 Fix where the ADR files trigger CODEOWNERS
  .github/CODEOWNERS
Labels: Pamplemoose, ready-to-merge, bug

#159 Organize the sidebar
  docs/guides/adrs/README.md
  docs/guides/adrs/template.md
  docusaurus.config.js
  sidebars.js
Labels: Pamplemoose, ready-to-merge, enhancement
