Repository transcom/mymove-docs, pull requests merged in 2023-07, with the labels that each got.

#366 Update testing.md with playwright test information
  docs/about/development/testing.md
Labels: ready-to-merge

#369 Configure JS tooling
  .eslintrc.js
  .prettierrc
  docusaurus.config.js
Labels: ready-to-merge, enhancement

#301 [ c-documentation ] Adding a warning that DoD Certificates page is out-of-date
  docs/about/security/dod-certs.md
Labels: Pamplemoose, ready-to-merge, infra, help wanted, enhancement

#376 Updating the `asdf` troubleshooting documentation
  docs/backend/guides/how-to/manage-golang-with-asdf.md
Labels: Pamplemoose, ready-to-merge, dependencies, bug

#383 MB-16460: Add link to prime v2 docs
  docusaurus.config.js
  sidebars.js
Labels: Huckleberry

#384 MB-16460: Update ADR based on implementation PR
  docs/adrs/0078-api-versioning.md
  docs/adrs/0080-api-versioning-based-on-test-run.md
Labels: ready-to-merge
