Repository transcom/mymove-docs, pull requests merged in 2023-02, with the labels that each got.

#287 MB-15044 Documentation for deploy app client tls
  docs/tools/cicd/circleci/deploy-app-client-tls.md
Labels: documentation

#281 MB-15044 Document the GitHub Actions for Happo
  docs/tools/cicd/github_actions/happo-tests-main.md
  docs/tools/cicd/github_actions/happo-tests.md
Labels: documentation

#291 Enable a hideable sidebar
  docusaurus.config.js
Labels: documentation, ready-to-merge, enhancement

#295 Fix various broken links for fresh brew
  README.md
  docs/about/application-setup/base-setup/homebrew.md
  docs/about/application-setup/setup-manually/prerequisites.md
Labels: documentation

#292 MB-14922 Reorganize the README
  docs/about/application-setup/additional-setup/login-gov.md
  docs/about/development/creating-alternative-users-with-the-same-email-address.md
  docs/about/development/goland.md
  docs/about/development/how-to-create-and-submit-PR.md
Labels: documentation

#297 MB-15032 - ADR to address storing origin duty GBLOC data
  docs/adrs/0077-permanently-store-origin-duty-gbloc.md
Labels: Huckleberry
