Repository transcom/mymove-docs, pull requests merged in 2023-06, with the labels that each got.

#363 [ MB-16175 ] Have deploy workflow run on a schedule
  .github/workflows/deploy.yml
Labels: Pamplemoose, ready-to-merge, enhancement

#350 MB-16176 - Create coverage ADR
  docs/adrs/0079-develop-strategy-for-ensuring-code-test-coverage.md
Labels: Pamplemoose

#364 Update examples in the Go Testing guide
  docs/backend/testing/run-go-tests.md
Labels: Pamplemoose, ready-to-merge

#362 [ MB-16175 ] Updating Redocly local documentation
  docs/tools/docusaurus/redocusaurus.md
Labels: documentation, Pamplemoose, ready-to-merge, enhancement
