Repository transcom/mymove-docs, pull requests merged in 2023-01, with the labels that each got.

#231 MB-14102 - Add partial updates ADR
  docs/adrs/0076-partial-update-patches.md
Labels: Pamplemoose

#273 Added a page called how to create & submit a PR under About section
  docs/about/how-to-create-and-submit-PR.md
  static/img/create_pr/categories_side_panel.png
  static/img/create_pr/compare_pr.png
  static/img/create_pr/happo_diffs.png
  static/img/create_pr/labels.png
  static/img/create_pr/merge.png
  static/img/create_pr/merge_conflicts.png
  static/img/create_pr/merge_success.png
  static/img/create_pr/mergify.png
  static/img/create_pr/open_pr.png
  static/img/create_pr/ready_to_merge.png
  static/img/create_pr/reviewers.png
Labels: documentation, ready-to-merge

#258 Adding automation around ADR authoring
  README.md
  docs/guides/adrs/README.md
  docs/guides/adrs/template.md
  package.json
  scripts/new-adr.sh
Labels: documentation, help wanted, enhancement

#277 MB-15044 Add documentation for the GitHub Action Auto Approve
  docs/tools/cicd/github_actions/auto-approve.md
Labels: documentation

#278 [ MB-15044 ] Add GitHub code blocks to the documentation
  docusaurus.config.js
  package.json
  yarn.lock
Labels: dependencies, infra, enhancement

#275 MB-15044 Add documentation for the GitHub Action Front End Linter
  docs/tools/cicd/github_actions/front-end-linter.md
Labels: documentation

#279 MB-15044 Use Code Block for the Auto Approve Documentation
  docs/tools/cicd/github_actions/auto-approve.md
Labels: documentation

#280 MB-15044 Add documentation for the GitHub Action go auto approve
  docs/tools/cicd/github_actions/go-auto-approve.md
Labels: documentation

#276 MB-15044 Add documentation for the GItHub Action Analyze Bundle
  docs/tools/cicd/github_actions/analyze-bundle.md
Labels: documentation
